version: '3.4'

services:

  db:
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: delivery-points
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 54320:5432
  app:
    build: .
    image: delivery-points:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: 'container'
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./recording:/app/recordings